#!/system/bin/sh

echo 1200000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 100000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

echo "Setting voltages"
cd /sys/kernel/liveopp
for f in 100 200 300 400 500 600 700 800 900 1000 1050 1100 1150 1200 1250 1300 1350 1400 1450; do
	fname=`grep -l -e ":[^0-9]*${f}000 kHz" arm_step* || echo /dev/null`
	eval f${f}=$fname
	echo set_volt=1 > $fname
done

source /data/boot.d/functions

# crash at 0xA(busy loop)
set_varm 100 0xc
# crash at 0x0a
set_varm 200 0x0d
set_varm 300 0x11
# instant crash at 0x0e, 0x0f stable for 180s
set_varm 400 0x12
# crash at 0x13
set_varm 500 0x16
# crsh at0x18, 0x19 unstable
set_varm 600 0x1b
# crash at 0x1c
set_varm 700 0x1f
#0x24
set_varm 800 0x26
#0x25
set_varm 900 0x2B
#0x2d unstable, 0x2e stable for 180s
set_varm 1000 0x2f
# Vbbx=0xdb, 0x26 unstable
# Vbbx=0x00, 0x2E unstable
set_vbbx 1050 0x00
set_varm 1050 0x30
# Vbbx=0xf9, 0x2F unstable
set_vbbx 1100 0xf9
set_varm 1100 0x31
# Vbbx=0xe8, 0x32 unstable XXX bad Vbbx (-200, 0)
# Vbbx=0xdb, 0x2C unstable
# Vbbx=0xea, 0x2F unstable
set_vbbx 1150 0xea
set_varm 1150 0x31
# Vbbx=0x8f, 0x2B unstable, Pa=1311mW
# Vbbx=0xdb, 0x2F unstable, Pa=1256mW
# Vbbx=0xdb, 0x31 had crashes
set_vbbx 1200 0xdb
set_varm 1200 0x32
# Vbbx=0xcc, 0x2C unstable
# Vbbx=0xdb, 0x32 unstable
set_vbbx 1250 0xdb
set_varm 1250 0x34
#set_vbbx 1250 0xcc
#set_varm 1250 0x2E
# Vbbx=0xdb, 0x36 crash (450mA)
# Vbbx=0xcc, 0x32 crash (430mA)
set_vbbx 1300 0xcc
set_varm 1300 0x34

#Vbbx=0x8f, 0x34 crash (500mA)
#Vbbx=0xcc, 0x35 crash (475mA), 0x36 unstable?
set_vbbx 1350 0xcc
set_varm 1350 0x38

# Vbbx
# 0x44 = (400, -400)
# 0x33 = (300, -300)
# 0x22 = (200, -200)
# 0x11 = (100, -100)
# 0x00 = (0, 0)
# 0xf9 = (-100, 100)
# 0xea = (-200, 200)
# 0xdb = (-300, 300)
# 0xcc = (-400, 400)
# 0x8f = (-400, 400) or (-800, 700)? best oc/uv

# 0xe8 = (-200, 0)
