#!/system/bin/sh

. /data/boot.d/functions

insmod /lib/modules/cpufreq_dynamic.ko
echo 100000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq 
#echo 800000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq 

set_gov dynamic

#gov_set_param down_threshold 40
#gov_set_param up_threshold 99
gov_set_param _sampling_rate 20000
gov_set_param up_threshold 90
gov_set_param standby_sampling_rate 20000
gov_set_param sampling_down_factor 2
gov_set_param standby_delay_factor 1
gov_set_param standby_sampling_up_factor 4
gov_set_param suspend_sampling_up_factor 5

gov_set_param io_is_busy 15
gov_set_param ignore_nice_load 1

gov_set_param sampling_down_factor_relax 3
gov_set_param k 0

gov_set_param input_boost_freq 400000
gov_set_param input_boost_ms 100

echo off > /sys/kernel/mxt224e/touchboost

exit 0
